### ISSUE TITLE
[FEATURE] Record meta data of the extension for intelligent operations

### ISSUE THREAD

**Issue by sheepzh** [sheepzh/timer#58]
- [x] The first installation time
- [x] The visit count of app page
- [x] The visit count of popup page
